# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "22d8de28474382e3b36d91d26ba8fc37"
application_url = "https://like-publishers-using-bachelor.trycloudflare.com"
embedded = true
name = "dashbot-app"
handle = "dashbot-app"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_orders,write_orders,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects,read_customers,write_customers"

[auth]
redirect_urls = [
  "https://like-publishers-using-bachelor.trycloudflare.com/auth/callback",
  "https://like-publishers-using-bachelor.trycloudflare.com/auth/shopify/callback",
  "https://like-publishers-using-bachelor.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "mvptestingstore.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
